name: publish-pack
on: [push, workflow_dispatch]
jobs:
  publish-pack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install CodeQL
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh extension install github/gh-codeql
          gh codeql set-version latest
      - name: Download Pack
        env: 
          GH_TOKEN: ${{ github.token }}
        run: |
          echo $GH_TOKEN | gh codeql pack download --github-auth-stdin advanced-security-demo/javascript-queries
