name: publish-pack
on: [push, workflow_dispatch]
jobs:
  publish-pack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install GitHub Auth
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release download -R advanced-security/github-app-auth --pattern github-app-auth-linux -O github-app-auth
          chmod +x github-app-auth
      - name: Install CodeQL
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh extension install github/gh-codeql
          gh codeql set-version latest
      - name: Test pack
        run: |
          gh codeql pack install javascript-queries
          gh codeql test run javascript-queries
      - name: Publish pack
        env:
          APP_ID: ${{ secrets.APP_ID }}
          PRIVATE_KEY_BASE64: ${{ secrets.PRIVATE_KEY_BASE64 }}
        run: |
          ./github-app-auth $APP_ID <($PRIVATE_KEY_BASE64 | base64 -d) | gh codeql pack publish --github-auth-stdin javascript-queries
